drop table tb_movimenti;


CREATE TABLE `tb_movimenti` (
  `DATA_OPERAZIONE` date NOT NULL,
  `DATA_VALUTA` date NOT NULL,
  `CAUSALE_ESTESA` varchar(255) NOT NULL,
  `IMPORTO` decimal(65,2) NOT NULL,
  `CAUSALE_CODICE` varchar(4) NOT NULL DEFAULT '0000',
  `LOAD_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ID_TB_MOVIMENTI` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID_TB_MOVIMENTI`,`CAUSALE_ESTESA`,`IMPORTO`,`CAUSALE_CODICE`,`LOAD_TIMESTAMP`,`DATA_VALUTA`,`DATA_OPERAZIONE`),
  KEY `ID_TB_MOVIMENTI` (`ID_TB_MOVIMENTI`)
) ENGINE=InnoDB AUTO_INCREMENT=6143 DEFAULT CHARSET=latin1;

select CAUSALE_ESTESA from tb_movimenti



LOAD DATA INFILE 'C:\\datidavide\\tempWD\\Movimenti-SQL.csv' INTO TABLE movimenti.tb_movimenti
( DATA_OPERAZIONE,DATA_VALUTA,CAUSALE_ESTESA,IMPORTO,CAUSALE_CODICE)    
  SET LOAD_TIMESTAMP = CURRENT_TIMESTAMP; 